### ISSUE TITLE
Bower package

### ISSUE THREAD

**Issue by felixgirault** [MoonScript/jQuery-ajaxTransport-XDomainRequest#19]
Hi,

Thanks for this script, it works like a charm!
I just wanted to know if you considered registering it as a bower package?

Cheers

**Comment by ghost** [comment]
Did this end up being registered on Bower repos?

**Comment by MoonScript** [comment]
@rosbritebill it looks like it:
http://bower.io/search/?q=jquery.xdomainrequest

**Comment by ghost** [comment]
Nice, I couldn't find it on a quick search, maybe a reference in the readme would be helpful.
Install via bower:
 bower install jQuery.XDomainRequest  --save
