### ISSUE TITLE
POST XDR With Headers and jQuery

### ISSUE THREAD

**Issue by bimco-dbj** [MoonScript/jQuery-ajaxTransport-XDomainRequest#42]
Hi Everyone,

Moonscript, I found my way to https://github.com/MoonScript/jQuery-ajaxTransport-XDomainRequest/issues/1 upon encountering an error 500 using your inplace XDR.
It does seem to go a bit further than vanilla $.ajax, so it's a little better.

On 11th of October, you pointed out that content-type as text/plain was a requirement of XDR, and supplied a few links:

> @jeroenooms More info in item number 4 on [this page](http://blogs.msdn.com/b/ieinternals/archive/2010/05/13/xdomainrequest-restrictions-limitations-and-workarounds.aspx) about posting as text/plain.

I'm about to parse as json server side, and wrap all text/plain calls in this little preprocess -step, but I'm hesitating, because the link you supplied states that "No custom headers may be added to the request"
Now, do I have to work around this as well, effectively turning the entire request into a plain-text message?

Thanks in advance, and thank you for your work.

**Comment by MoonScript** [comment]
@bimco-dbj yes, when you use the *XDomainRequest* object, it's essentially a completely anonymous request (no cookies, no custom headers), which only allows `text/plain` POSTs.

**Comment by tracker1** [comment]
@bimco-dbj if you control both sides of the request, you may want to consider something like [xdomain](https://github.com/jpillora/xdomain) as a shim for older IE browsers.

**Comment by marine-dj** [comment]
Thank you both, it was good to get confirmed, and @tracker1 - I'll look into that shim. It was exactly due to IE the entire time.
