### ISSUE TITLE
Doesn't work with protocol-relative URLs

### ISSUE THREAD

**Issue by Dygerati** [MoonScript/jQuery-ajaxTransport-XDomainRequest#43]
Right now the module is hard-coded to enforce the usage of HTTP/HTTPS, as well as ensuring that the current page and request URL have matching schemes. This is just done using simple regex, and doesn't account for a protocol-relative URL that doesn't specify the protocol (http://www.paulirish.com/2010/the-protocol-relative-url/). 

I find these types of URLs useful and use them frequently. Just thought I'd mention it! Works beautifully once I removed the checks, so thanks!

Joel T

**Comment by MoonScript** [comment]
@Dygerati this has been [fixed](39) by @laurens.
