### ISSUE TITLE
v1.0.3 release

### ISSUE THREAD

**Issue by kevin-bonnin** [MoonScript/jQuery-ajaxTransport-XDomainRequest#45]
Hi, I'm using rails-assets to get bower packages into my application, and I get an error message because the bower.json file is not included in the package. I can see you included it with v1.0.3 but it's not released (tagged) yet and thus not available from rails-assets.org

It'd be great if you could release it so we could get rid of those errors ;)

**Comment by raycohen** [comment]
+1

**Comment by s0ber** [comment]
+1, release it please.

**Comment by MoonScript** [comment]
Released!
https://github.com/MoonScript/jQuery-ajaxTransport-XDomainRequest/releases/tag/1.0.3

Sorry for the delay, guys.  I think I was waiting on **cdnjs** when I first had this release ready, then forgot to back and tag it in my repo.
