### ISSUE TITLE
code bug

### ISSUE THREAD

**Issue by webyonet** [MoonScript/jQuery-ajaxTransport-XDomainRequest#47]
if(...  !sameSchemeRegEx.test(options.url))

This code is not crossdomain?
This plugin does not work on ie8.
sample:
sameScheme = "http://"
options.url = "https://blabla.com"
this logic always false

**Comment by MoonScript** [comment]
Correct, the *XDomainRequest* object cannot make requests from `http://` to `https://` or vice-versa.
