### ISSUE TITLE
Notseeing Content Type in IE

### ISSUE THREAD

**Issue by jaybillhighway** [MoonScript/jQuery-ajaxTransport-XDomainRequest#49]
I understand on IE we default to contentType: 'text/plain' however I do not see this in the HTTP request hedder. 

Jay

**Comment by jaybillhighway** [comment]
Found out that XDomainRequest doesn't appear to send any Content-Type header at all so I have to handle this on the server side. Love this code snipset - Jay

**Comment by MoonScript** [comment]
@jaybillhighway right, I just confirmed this using [Fiddler](http://www.telerik.com/fiddler) in IE8.  Here's the full content of my request, including all of the request headers:

```
POST http://moonscript.jsapp.us/ HTTP/1.1
Accept: */*
Origin: http://fiddle.jshell.net
Accept-Language: en-us
Accept-Encoding: gzip, deflate
User-Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0; .NET CLR 2.0.50727; .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729)
Host: moonscript.jsapp.us
Content-Length: 55
Connection: Keep-Alive
Pragma: no-cache

data sent to the server on Fri Mar 13 12:15:59 CDT 2015
```

**Comment by Array-Huang** [comment]
so that is it ? no bug-fix ? or this is not a bug ?

**Comment by tracker1** [comment]
IE's XDomainRequest is _REALLY_ limited... you can get a little more by using an IFrame funnel with postMessage...  It cannot be fixed, it can only be worked around.

**Comment by Array-Huang** [comment]
Pity that. At last, I decided to use a lib which in proxy way: https://github.com/jpillora/xdomain
