### ISSUE TITLE
Package appears a bunch of times in bower search

### ISSUE THREAD

**Issue by EdwardIII** [MoonScript/jQuery-ajaxTransport-XDomainRequest#51]
Very small thing but I noticed the package shows up a bunch of times in bower search:

```
$ bower search XDomainRequest
jQuery.XDomainRequest git://github.com/MoonScript/jQuery-ajaxTransport-XDomainRequest.git
jquery.xdomainrequest git://github.com/MoonScript/jQuery-ajaxTransport-XDomainRequest.git
jquery-ajaxtransport-xdomainrequest git://github.com/MoonScript/jQuery-ajaxTransport-XDomainRequest.git
```

I just arbitrarily picked one but if possible it might be a bit nicer if it just had one (jquery-ajaxtransport-xdomainrequest seems most consistent with other package names).

**Comment by MoonScript** [comment]
I'm not that familiar with Bower. If you know how to fix this, could you please submit a pull request?
