### ISSUE TITLE
IE8 Always Failing 

### ISSUE THREAD

**Issue by omarmeky** [MoonScript/jQuery-ajaxTransport-XDomainRequest#54]
I have included your plugin and am trying to run something like this:

```
$.ajax({
    type: 'GET',
    url: 'http://10.0.0.2/',
    dataType: 'text',
    data: getParams(),
    success: successCB,
    error: errorCB
});
```

I continuously get an error. For some reason `xdr.onerror` is always called. Do you know what the issue is?

**Comment by tracker1** [comment]
What is the error receiving?  Have you run it with fiddler to see what the server's response is, or what the client is sending?  Are other browsers working?

**Comment by omarmeky** [comment]
Chrome is working so the request itself is fine. Here is the error output I receive in IE8:

```
LOG: jqXHR: {"readyState":4,"responseText":"null","status":500,"statusText":"error"}
LOG: textStatus: error
LOG: errorThrown: error
```

**Comment by MoonScript** [comment]
@omarmeky it would really help if you could put this up on [jsFiddle](http://jsfiddle.net/) so we could help debug.

**Comment by tracker1** [comment]
@omarmeky are you relying on being able to set specific headers?  XDR doesn't support setting headers (except content type) with IE8-10... [xdomain](https://github.com/jpillora/xdomain) may work out better for you.

**Comment by tonyabra** [comment]
Ran into something similar. If it helps anyone, we had issues with the Access-Control-Allow-Origin-header returned from the server. IE8 can be very picky about what you're sending back.
