### ISSUE TITLE
Not working with sending JSON

### ISSUE THREAD

**Issue by hzxie** [MoonScript/jQuery-ajaxTransport-XDomainRequest#55]
I wrote following code:

```
var config = {
    'appid': gaeAppId,
    'passwd': gaePassword,
};

$.ajax({
    type: 'POST',
    url: 'http://127.0.0.1:8084/config?cmd=set_config',
    data: config,
    dataType: 'JSON',
    success: function(result) {
        console.log(result);
    }
});
```

This works fine in Chrome, but not working in IE 8.
The Ajax request is successful in IE 8, but the server response that didn't receive the POST variable `appid`.

So I wrote the code as the document said:

```
var config = {
    'appid': gaeAppId,
    'passwd': gaePassword,
};

$.ajax({
    url: 'http://127.0.0.1:8084/config?cmd=set_config',
    data: config,
    contentType: 'text/plain',
    type: 'POST',
    dataType: 'json'
}).done(function(result) {
    console.log(result);
});
```

This code not working in Chrome and IE.
The Ajax request is successful in the two browsers, but the server response that didn't receive the POST variable `appid`.

I think there's something wrong with your code.
Please help me.

**Comment by tracker1** [comment]
try this...

``` js
  ...
  ,data: JSON.stringify(config)
  ,contentType: 'application/json'
  ...
```

**Comment by hzxie** [comment]
Still not working.

The URL of web page is `http://127.0.0.1:8085/?module=goagent&menu=config`.
The Ajax is code is:

```
$.ajax({
    url: 'http://127.0.0.1:8084/config?cmd=set_config',
    data: config,
    contentType: 'application/json',
    type: 'POST',
    dataType: 'JSON'
}).done(function(result) {
    console.log(result);
});
```

The Chrome returns the error message that `XMLHttpRequest cannot load http://127.0.0.1:8084/config?cmd=set_config. Request header field Content-Type is not allowed by Access-Control-Allow-Headers.`.

**Comment by MoonScript** [comment]
@zjhzxhz sounds like you have to remove the `contentType` option (since the XDR option does not set it).

**Comment by tracker1** [comment]
@zjhzxhz Do you have CORS setup properly on the destination host?

**Comment by JokerQyou** [comment]
I'm having the same issue, I have CORS setup properly on the destination host, I know this because I can directly use `$.ajax()` to access it in Chrome when I'm not using your plugin. And now I want to add support for IE 8, and things become mysterious. Nothing is wrong with the scripts, but the server on the destination host receives 0 length request with no post data. And by manually executing `$.ajax()` in developer tool, an error tell me that there is a 500 server error, yet my server receives no request.

**Comment by MoonScript** [comment]
When posting, the IE XDR object will only send the data as `text/plain`, so your server has to be prepared to handle that.

**Comment by JokerQyou** [comment]
Exactly. I've managed to solve this on my server side few momths ago. For Python flask server, the data is in request.data, and for Python pyramid server, the data is in request.text. All of which are not the usual way of getting parameters or POST data.
