### ISSUE TITLE
Is there an npm package for this?

### ISSUE THREAD

**Issue by DanielNill** [MoonScript/jQuery-ajaxTransport-XDomainRequest#57]
I can't find one. It would be really nice to have one.

**Comment by Reggino** [comment]
+1

It seems there in `package.json`, just needs an `npm publish`...?

**Comment by vvo** [comment]
@MoonScript can you npm publish this please?

**Comment by vvo** [comment]
just published the package as 'jquery-ajax-transport-xdomainrequest' let me know @MoonScript if you need to be maintainer on npm..

**Comment by MoonScript** [comment]
@vvo thanks for doing that.  I must admit that I had no idea on what that meant to "publish" as an npm package.  But yes, could you please add me as a maintainer on npm, since I would presumably be the one who would have to push future updates there?
(would I do that via `npm publish`?)

**Comment by vvo** [comment]
Yes exactly @MoonScript , will add you on monday

**Comment by DanielNill** [comment]
sounds like this is resolved. Closing 😄
